name: Build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install tools
      run: |
        sudo apt-get install autopoint automake pkg-config texinfo

    - name: Bootstrap
      run: | 
        ./bootstrap

    - name: Configure
      run: |
        ./configure
    
    - name: Compile
      run: |
        make

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: make
        path: make