name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install tools
      run: |
        apt-get install autopoint automake

    - name: Bootstrap
      run: | 
        ./bootstrap

    - name: Configure
      run: |
        ./configure
    